# Generated by Django 5.1.1 on 2024-09-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='findings',
            field=models.TextField(blank=True),
        ),
    ]
