# Generated by Django 5.1.1 on 2024-10-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='ai_default.jpg', null=True, upload_to='ai_images/'),
        ),
    ]
