# Generated by Django 5.1.1 on 2024-11-11 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_analysis'),
        ('blog', '0004_newscard'),
    ]

    operations = [
    ]
