spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/curatednews
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: curated

  flyway:
    schemas: curated

logging:
  level:
    root: INFO
    com.curatedNews: DEBUG
