# Generated by Django 5.1.1 on 2024-09-11 04:31

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=50)),
                ('prompt', models.CharField(max_length=100)),
                ('findings', models.TextField()),
                ('date_range_start', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('date_range_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
